import "@fortawesome/fontawesome-svg-core/styles.css"
import { Inter } from "next/font/google"
import "./globals.css"

import { config } from "@fortawesome/fontawesome-svg-core"
import { faInfoCircle } from "@fortawesome/free-solid-svg-icons"
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome"
config.autoAddCss = false

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	const currentYear = new Date().getFullYear()
	return (
		<html lang="en">
			<body className={inter.className}>
				<main className="min-h-screen max-w-screen container bg-white mx-auto relative">
					<button className="h-9 absolute top-3 right-3 bg-info/20 hover:bg-info/25 z-10 px-4 flex justify-center items-center rounded-full">
						<FontAwesomeIcon
							icon={faInfoCircle}
							color={"#008BFF"}
							className="mr-1 h-5 w-5"
						/>
						<p className="text-info text-sm font-semibold">Help</p>
					</button>

					<section className="min-h-screen flex flex-col justify-center items-center">
						{children}
					</section>

					<section className="absolute left-0 bottom-0 right-0 flex justify-center items-center py-6">
						<p className="text-grey text-sm">
							{currentYear} Smartness SAS - kopain ©
						</p>
					</section>
				</main>
			</body>
		</html>
	)
}
